import {readFile,writeFile,mkdir,cp,rm} from 'node:fs/promises';
import {yearData,monthlyData,hhmm,MONTHS} from '../cambio-de-hora/solar.mjs';
const root=new URL('../',import.meta.url), out=new URL('../dist/',import.meta.url);
await rm(out,{recursive:true,force:true});await mkdir(new URL('cambio-de-hora/',out),{recursive:true});
const home=await readFile(new URL('index.html',root),'utf8');
for(const file of ['index.html','robots.txt','sitemap.xml'])await cp(new URL(file,root),new URL(file,out));
for(const file of ['story.css','story.mjs','solar.mjs','social.png'])await cp(new URL('cambio-de-hora/'+file,root),new URL('cambio-de-hora/'+file,out));
const kit=home.match(/^.*(?:<link[^>]+(?:style\.css|rel="icon")|<script[^>]+(?:theme\.js|chrome\.js)).*$/gm).join('\n');
let header=home.match(/<header class="gr-nav">[\s\S]*?<\/header>/)[0];
header=header.replace(/href="#que-es-cochid"/g,'href="/#que-es-cochid"').replace(/href="#productos"/g,'href="/#productos"').replace(/href="#servicios"/g,'href="/#servicios"');
header=header.replace(/<div class="gr-nav__group">[\s\S]*?<\/div>/,'<div class="gr-nav__group"><a class="gr-nav__link" href="#explorar">Explorar</a><a class="gr-nav__link" href="#argumento">El argumento</a><a class="gr-nav__link" href="#graficos">El año</a><a class="gr-nav__link" href="#metodo">Datos y fuentes</a></div>');
let page=await readFile(new URL('cambio-de-hora/index.html',root),'utf8'),days=yearData(),months=monthlyData(days);
page=page.replace('<!--KIT_HEAD-->',kit).replace('<!--HEADER-->',header).replace('<!--FOOTER-->',home.match(/<footer class="gr-footer">[\s\S]*?<\/footer>/)[0]);
page=page.replace('<!--MONTH_BUTTONS-->',MONTHS.map((m,i)=>`<button type="button" aria-pressed="${i===8}" aria-label="Ver promedios de ${m}">${m}</button>`).join(''));
page=page.replace('<!--MONTH_TABLE-->',months.map(m=>`<tr><th scope="row">${m.name}</th><td>${hhmm(m.riseLegal)}</td><td>${hhmm(m.setLegal)}</td><td>${hhmm(m.riseFixed)}</td><td>${hhmm(m.setFixed)}</td><td>${Math.round(m.daylight)}</td><td>${Math.round(m.change)}</td></tr>`).join('\n'));
await writeFile(new URL('cambio-de-hora/index.html',out),page);
const dailyHeader='fecha,huso_vigente,salida_vigente,puesta_vigente,salida_UTC_menos4,puesta_UTC_menos4,luz_minutos,crepusculo_inicio_UTC_menos4,crepusculo_fin_UTC_menos4';
await writeFile(new URL('cambio-de-hora/santiago-2026-diario.csv',out),dailyHeader+'\n'+days.map(d=>[d.date,d.offset,hhmm(d.riseLegal),hhmm(d.setLegal),hhmm(d.riseFixed),hhmm(d.setFixed),d.daylight.toFixed(3),hhmm(d.dawnFixed),hhmm(d.duskFixed)].join(',')).join('\n')+'\n');
await writeFile(new URL('cambio-de-hora/santiago-2026-mensual.csv',out),'mes,dias,salida_vigente,puesta_vigente,salida_UTC_menos4,puesta_UTC_menos4,luz_media_minutos,cambio_primer_a_ultimo_dia_minutos\n'+months.map(m=>[m.name,m.days,hhmm(m.riseLegal),hhmm(m.setLegal),hhmm(m.riseFixed),hhmm(m.setFixed),m.daylight.toFixed(3),m.change.toFixed(3)].join(',')).join('\n')+'\n');
console.log(`Sitio estático: ${days.length} días, ${months.length} promedios; chrome compartido y CSV exportados en dist/.`);
