const escapar=texto=>String(texto).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');

export function paginaHilo(hilo){
  const titulos=['Aporte fiscal libre','Nominal y real','Cambios por sector','Seguridad con el mismo perímetro','Subsidios de empleo','Qué falta comprobar'];
  const filas=hilo.tweets.map((tweet,i)=>{
    if([...tweet.texto].length>280)throw new Error('El tweet supera 280 caracteres');
    if(!/^[a-z0-9-]+\.png$/.test(tweet.grafico)||!tweet.alt)throw new Error('El gráfico requiere un PNG propio y texto alternativo');
    return `<li class="hilo-item"><h2>${i+1}. ${titulos[i]||'Presupuesto 2027'}</h2><div class="hilo-fila"><div><label for="tweet-${i+1}">Texto del tweet ${i+1} (${[...tweet.texto].length} caracteres)</label><textarea id="tweet-${i+1}" rows="6" readonly>${escapar(tweet.texto)}</textarea><button type="button" class="btn-primary" data-copiar-tweet="tweet-${i+1}">Copiar tweet ${i+1}</button></div><figure class="blog-figura"><img src="/assets/presupuesto-2027/${tweet.grafico}" alt="${escapar(tweet.alt)}" loading="lazy"><figcaption>Fuente y alcance en la imagen. Corte: 5 de octubre de 2026. <a href="/assets/presupuesto-2027/${tweet.grafico}" download="presupuesto-2027-tweet-${i+1}-${tweet.grafico}">Descargar PNG del tweet ${i+1}</a></figcaption></figure></div></li>`;
  });
  return `<p>Seis textos listos para copiar con sus gráficos. Compara el proyecto oficial 2027 con la ley inicial 2026. Los ajustes reales usan inflación hipotética de 3%. <strong>No se envía a X.</strong></p><p><a href="${hilo.analisis}">Leer el análisis, fuentes y método</a> · <a href="https://datos.cochid.cl/presupuesto/proyecto">Seguir la propuesta</a> · <a href="https://periodismo2.cl/article/c4eb0791-4c19-59d7-9465-1fc53e25290a">Leer la noticia en Periodismo2</a></p><button class="btn-primary" type="button" data-copiar-hilo>Copiar hilo completo</button><p class="hilo-estado" role="status" aria-live="polite" data-hilo-estado></p><p>También puedes seleccionar y copiar el texto de cada casilla. La descarga incluye el PNG original.</p><ol class="hilo-lista">${filas.join('')}</ol><p><a href="/assets/presupuesto-2027/hilo.txt" download="presupuesto-2027-hilo.txt">Descargar todos los textos</a> · <a href="/assets/presupuesto-2027/comparacion.csv">Descargar datos CSV</a></p><script src="/assets/presupuesto-2027/hilo.js" defer></script>`;
}
